```{r}
if(!require("EBImage")){
  install.packages("BiocManager")
  BiocManager::install("EBImage")
}
if(!require("R.matlab")){
  install.packages("R.matlab")
}
if(!require("readxl")){
  install.packages("readxl")
}

if(!require("dplyr")){
  install.packages("dplyr")
}
if(!require("readxl")){
  install.packages("readxl")
}

if(!require("ggplot2")){
  install.packages("ggplot2")
}

if(!require("caret")){
  install.packages("caret")
}

if(!require("glmnet")){
  install.packages("glmnet")
}

if(!require("WeightedROC")){
  install.packages("WeightedROC")
}

library(R.matlab)
library(readxl)
library(dplyr)
library(EBImage)
library(ggplot2)
library(caret)
library(glmnet)
library(WeightedROC)
```

```{r}
# setwd("~/Spring2021-Project3-group-2")
label_list <- read.csv("./data/train_set/label.csv")
label_list$label[label_list$label==0] <- 'Compounded'
label_list$label[label_list$label==1] <- 'Basic'

g1 <- ggplot(data = label_list, aes(x=factor(label))) + geom_bar(mapping = aes(x = label)) +
  labs(title="Sample Count of Class", x="label", y = "count") +
  geom_text(aes(label=..count..),stat='count')
plot(g1)
```